src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 */
class Annonce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="Annonces")
     * @ORM\JoinColumn(nullable=true)
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=Crypto::class, inversedBy="Annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $crypto;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @Gedmo\Slug(fields={"titre"})
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;
    /**
    * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="Annonce", orphanRemoval=true)
     */
    private $Commentaires;

    public function __construct()
    {
        $this->createdAt = new \DateTime;
        $this->Commentaires = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getCrypto(): ?Crypto
    {
        return $this->crypto;
    }

    public function setCrypto(?Crypto $crypto): self
    {
        $this->crypto = $crypto;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->Commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->Commentaires->contains($commentaire)) {
            $this->Commentaires[] = $commentaire;
            $commentaire->setAnnonce($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->Commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getAnnonce() === $this) {
                $commentaire->setAnnonce(null);
            }
        }


        return $this;
    }

}

src/Entity/Liste.php
<?php

namespace App\Entity;

use App\Repository\ListeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ListeRepository::class)
 */
class Liste
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Users::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\ManyToMany(targetEntity=Crypto::class, inversedBy="listes")
     */
    private $Cryptos;

    public function __construct()
    {
        $this->Cryptos = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->User;
    }

    public function setUser(Users $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Crypto>
     */
    public function getCryptos(): Collection
    {
        return $this->Cryptos;
    }

    public function addCrypto(Crypto $crypto): self
    {
        if (!$this->Cryptos->contains($crypto)) {
            $this->Cryptos[] = $crypto;
        }

        return $this;
    }

    public function removeCrypto(Crypto $crypto): self
    {
        $this->Cryptos->removeElement($crypto);

        return $this;
    }

}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use App\Entity\Annonce;
use App\Entity\Crypto;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder  
            ->add('titre',TextType::class)
            ->add('crypto' ,EntityType::class, [
                'class'=>Crypto::class,
                'label'=>'Crpto'
            ])
            ->add('description',TextareaType::class, ['required' => false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Entity\Commentaire;
use App\Form\AnnonceType;
use App\Form\CommentaireType;
use App\Entity\Users;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use App\Repository\AnnonceRepository;

class AnnonceController extends AbstractController
{
    /**
     * @Route("/annonce", name="app_annonce")
     */
    public function index(): Response
    {
        return $this->render('annonce/index.html.twig', [
            'controller_name' => 'AnnonceController',
        ]);
    }
    /**
     * @Route("/listAnnonceUser", name="annonces_user")
     * @IsGranted("ROLE_USER")
     */
    public function listAnnonce(): Response
    {
        $annonces=$this->getDoctrine()->getRepository(Annonce::class)->getAnnonceById($this->getUser());
        return $this->render('annonce/userAnnonce.html.twig', [
            'annonces' => $annonces,
        ]);
    }

    /**
     * @Route("/annonce/ajout", name="ajout_annonce")
     * @IsGranted("ROLE_USER")
     */
    public function ajoutArticle(Request $request){
        $annonce= new Annonce();

        $form=$this->createForm(AnnonceType::class, $annonce);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $annonce->setUsers($this->getUser());
            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($annonce);
            $doctrine->flush();

            return $this->redirectToRoute('app_crypto_blog');
        }
        return $this->render('annonce/ajout.html.twig', [
            'annonceForm'=>$form->createView()
        ]);
    }
    /**
     * @Route("/show/{slug}", name="show_annonce")
     */
    public function show(Annonce $annonce, Request $request)
    {
        $commentaire = new Commentaire();
        $form=$this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);
        $commentaires = $this->getDoctrine()
            ->getRepository(Commentaire::class)
            ->getCommentByAnnonce($annonce->getId()
            );

        if($form->isSubmitted() && $form->isValid()){
            $commentaire->setUsers($this->getUser());
            $commentaire->setCreatedAt(new \DateTime());
            $commentaire->setAnnonce($annonce);
            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($commentaire);
            $doctrine->flush();
        }

        return $this->render('annonce/show.html.twig', [
            'annonce' => $annonce,
            'commentaireForm'=>$form->createView(),
            'commentaires' => $commentaires
        ]);
    }
    /**
     * @Route("/edit/{slug}", name="annonce_edit")
     * @IsGranted("ROLE_USER")
     */
    public function edit(Annonce $annonce, Request $request){

        $form=$this->createForm(AnnonceType::class, $annonce);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('annonces_user');
        }
        return $this->render('annonce/edit.html.twig', [
            'annonceForm'=>$form->createView()
        ]);
    }
    /**
     * @Route("/delete/{slug}", name="annonce_delete")
     * @IsGranted("ROLE_USER")
     */
    
     public function delete(Annonce $annonce){

        $em = $this->getDoctrine()->getManager();
        $em->remove($annonce);
        $em->flush();
        return $this->redirectToRoute('annonces_user'); 
    }
}

templates/annonce/ajout.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Ajouter une annonce{% endtrans %}{% endblock %}

{% block body %}
    <h1 class="title">{% trans %}Ajouter une annonce{% endtrans %}</h1>
    {{form_start(annonceForm)}}
    <div class="form-row">
        <div class="form-group col-md-6">
            <p>{% trans %}Titre{% endtrans %}</p>
            {{ form_widget(annonceForm.titre, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}}) }}
            <small class="text-danger">{{ form_errors(annonceForm.titre) }}</small>
        </div>
        <div class="form-group col-md-6">
            <p>Crypto</p>
            {{ form_widget(annonceForm.crypto, {'attr': {'class': 'selectpicker form-control'}}) }}
        </div>
    </div>
    <div class="form-group">
        <p>{% trans %}Déscription{% endtrans %}</p>
        {{ form_widget(annonceForm.description, {'attr': {'class': 'form-control', 'rows': 12}}) }}
    </div>
    <button type="submit" class="btn btn-primary button">{% trans %}Ajouter{% endtrans %}</button>
    {{ form_end(annonceForm) }}
{% endblock %}

templates/annonce/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer une annonce{% endblock %}
{% block body %}
    <h1 class="title">{% trans %}Editer{% endtrans %}</h1>
    {{form_start(annonceForm)}}
    <div class="form-row">
        <div class="form-group col-md-6 text-margin">
            {{ form_label(annonceForm.titre, 'Titre') }}
            {{ form_widget(annonceForm.titre, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}}) }}
            <small class="text-danger">{{ form_errors(annonceForm.titre) }}</small>
        </div>
        <div class="form-group col-md-6 text-margin">
            {{ form_label(annonceForm.crypto, 'Crypto') }}
            {{ form_widget(annonceForm.crypto, {'attr': {'class': 'selectpicker form-control'}}) }}
        </div>
    </div>
    <div class="form-group text-margin">
        {{ form_label(annonceForm.description, 'Description') }}
        {{ form_widget(annonceForm.description, {'attr': {'class': 'form-control', 'rows': 12}}) }}
    </div>
    <div class="edit-button">
        <a class="nav-link active" href="{{path('annonces_user')}}">
            <button type="button" class="btn btn-danger">{% trans %}Annuler{% endtrans %}</button>  
        </a>
        <button type="submit" class="btn btn-primary">{% trans %}Enregistrer{% endtrans %}</button>
    </div>
    {{ form_end(annonceForm) }}
{% endblock %}

templates/annonce/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ annonce.titre }}{% endblock %}

{% block body %}
<article class="container mt-4">
    <div class="row">
        <div class="col">
            <h1>{{ annonce.titre }}</h1>
            <p>Article créer le {{annonce.createdAt|format_date()}}</p>
            <div class="mt-4">
                {{ annonce.description}}<br>
            </div>
            <br>
            {% if app.user is not null %}
            <div>
                {{ form_start(commentaireForm) }}
                <h3 class="comment-title"> {%trans %} Votre commentaire : {%endtrans%} </h3>
                {{ form_widget
                    (commentaireForm.commentaire, {'attr' :
                        {'class' : 'form-control',
                            'placeholder' : 'Restez courtois'
                        }}
                    )
                }}
                <button type="submit" class="btn btn-secondary my-2 my-sm-0 button">Commenter</button>
                {{ form_end(commentaireForm) }}
            </div>
            {% endif %}
            {% if commentaires is not null %}
                <div>
                    <h3 class="comment-title"> {%trans %} Les commentaires : {%endtrans%}</h3>
                    <br>
                    {% for commentaire in commentaires %}
                        <div class="form-group">
                            <fieldset>
                                <label class="form-label mt-4 user-comment" for="readOnlyInput">{{ commentaire.users.getPseudo}}</label>
                                <p>{{ commentaire.createdAt.format('d/m/Y h:m') }}</p>
                                <input class="form-control" id="readOnlyInput" type="text" placeholder="{{ commentaire.commentaire }}" readonly="">
                            </fieldset>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>


</article>
{% endblock %}

templates/annonce/userAnnonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cryptoworld{% endblock %}

{% block body %}
  
    <h1 class="titre title">{% trans %}Liste des annonces{% endtrans %}</h1>
    <table class="table table-hover list">
        <tr class="table-dark">
          <th scope="col">#</th>
          <th scope="col">{% trans %}Titre de l'annonce{% endtrans %}</th>
          <th scope="col">{% trans %}Crypto{% endtrans %}</th>
          <th scope="col">{% trans %}Modifier{% endtrans %}</th>
          <th scope="col">{% trans %}Supprimer{% endtrans %}</th>
        </tr>
      {% set i=1 %}
      {% for annonce in annonces %}
          <tr class="table-secondary ">
            <td>{{i}}</td>
            <td><a href="{{ path('show_annonce', {'slug': annonce.slug}) }}">{{annonce.titre}}</a></td>
            <td>{{annonce.crypto.nom}}</td>
            <td><a href ="{{path('annonce_edit', {slug: annonce.slug})}}"><i class="fa-solid fa-pen icon"></i></span></a></td>
            <td><a href ="{{path('annonce_delete', {slug: annonce.slug})}}"><i class="fa-solid fa-trash icon"></i></i></span></a></td>
          </tr>
      {% set i=i+1 %}
      {% endfor %}
    </table>
  
{% endblock %}