src/Entity/Liste.php
<?php

namespace App\Entity;

use App\Repository\ListeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ListeRepository::class)
 */
class Liste
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Users::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\ManyToMany(targetEntity=Crypto::class, inversedBy="listes")
     */
    private $Cryptos;

    public function __construct()
    {
        $this->Cryptos = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->User;
    }

    public function setUser(Users $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Crypto>
     */
    public function getCryptos(): Collection
    {
        return $this->Cryptos;
    }

    public function addCrypto(Crypto $crypto): self
    {
        if (!$this->Cryptos->contains($crypto)) {
            $this->Cryptos[] = $crypto;
        }

        return $this;
    }

    public function removeCrypto(Crypto $crypto): self
    {
        $this->Cryptos->removeElement($crypto);

        return $this;
    }

}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Annonce::class, mappedBy="users")
     */
    private $Annonces;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="users")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pseudo;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function __toString() : string
    {
        return $this->getId();
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRoles(string $roles): self
    {
        if (!in_array($roles, $this->roles)) {
            $this->roles[] = $roles;
        }

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }


    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://bootswatch.com/5/morph/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="{{asset('assets/style/style.css')}}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        <script src="{{asset('assets/js/script.js')}}"></script>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                
                <a href="{{path('app_crypto_blog')}}"><img src="{{asset('assets/img/logo.png')}}" alt="erreur" class="logo"></a>
                <!-- <a class="navbar-brand" href="{{path('app_crypto_blog')}}">Cryptoworld</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{path('app_crypto_blog')}}">{% trans %}Annonces{% endtrans %}</a>
                        </li>
                        {%if app.user%}
                        <li class="nav-item">
                            <a class="nav-link" href="{{path('ajout_annonce')}}">{% trans %}Créer une annonce{% endtrans %}</a>
                        </li>
                        
                            <li class="nav-item">
                                <a class="nav-link" href="{{path('annonces_user')}}">{% trans %}Mes annonces{% endtrans %}</a>
                            </li>
                        {%endif%}
                    </ul>
                    {%if app.user %}
                        <p style="margin-right: 10px;">{% trans %}Bienvenue {% endtrans %} {{app.user.pseudo}} !</p>
                    {%endif%}
                    <div class="form-check form-switch">
                        <input class="form-check-input dark" type="checkbox" id="flexSwitchCheckDefault" onclick="myFunction()">
                    </div>
                    {%if not app.user%}
                    <a class="nav-link active" href="{{path('app_register')}}">
                        <button type="button" class="btn btn-primary">{% trans %}S'inscrire{% endtrans %}</button>  
                    </a>
                    
                    <a class="nav-link active" href="{{path('app_login')}}">
                        <button type="button" class="btn btn-success">{% trans %}Se connecter{% endtrans %}</button>  
                    </a>
                    {%endif%}
                    {%if app.user %}
                        <a class="nav-link active" href="{{path('app_logout')}}">
                        <button type="button" class="btn btn-danger">{% trans %}Se déconnecter{% endtrans %}</button>  
                    </a>
                    {%endif%}
                    {% for locale in locales %}
                        {% if locale != app.request.locale %}
                            <a href="{{ path('change_locale', {'locale': locale}) }}"><img src="{{asset('assets/img/'~locale~'.png')}}" alt="erreur" class="flag"></a>
                        {% endif %}
                    {% endfor %}
                    
                    {%if is_granted('ROLE_ADMIN') %}
                        <a href="{{path('admin_utilisateurs')}}"><img src="{{asset('assets/img/profil.png')}}" alt="erreur" class="profil"></a>
                    {% endif %}
                </div>
            </div>
            
        </nav>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
        
    </body>
</html>